config/routes.rb
# frozen_string_literal: true

# Main Router
Rails.application.routes.draw do
  namespace :reports do
    get :ward_list
    get :medications_list
    get :discharge_list
    get :patient_card
  end
  resource :invoice_payments
  resources :diagnoses
  resources :invoices do
    member do
      get :receive_payment
    end
    collection do
      post :set_payment_received
      # get :send_mail
    end
  end
  resources :wards do
    collection do
      match 'search' => 'wards#search', via: %i[get post], as: :search
    end
  end
  resources :drugs
  resources :patients
  resources :teams
  resources :treatments
  resources :prescriptions
  resources :staffs
  resources :specialities
  resources :job_titles
  resources :admissions do
    # Members require admission id
    member do
      get :discharge
      post :authorise_discharge
      patch :admit_scheduled
      delete :cancel_scheduled
    end
    # Collections do not require id
    collection do
      get :find_and_discharge
      match 'search' => 'admissions#search', via: %i[get post], as: :search
    end
  end

  # Find controller under search module and it is actions
  namespace :search do
    get :search, to: 'search#search', as: :search
    get 'find_admitted_patients_in_ward', to: 'find#find_admitted_patients_in_ward'
    get 'find_patients_discharge_unauthorised', to: 'find#find_patients_discharge_unauthorised'
    get 'find_discharged_without_invoice_patients_in_ward', to: 'find#find_discharged_without_invoice_patients_in_ward'
    get 'find_admitted_diagnosed_patients_in_ward', to: 'find#find_admitted_diagnosed_patients_in_ward'
  end

  # Change devise routes from staffs/login to /login
  devise_for :staffs, path: '',
             path_names: { sign_in: 'login', account_update: 'update' }

  # On the scope of devise, manage authenticated and unauthenticated users
  devise_scope :staff do
    authenticated :staff do
      root to: 'home#index'
    end
    unauthenticated :staff do
      root to: 'devise/sessions#new'
    end
  end

  get :home, to: 'home#index'

  root to: 'devise/sessions#new'

  # Handle errors, must be at end
  # Tell Router how to handle error by matching status code
  match '404' => 'errors#not_found', :via => :all
  match '406' => 'errors#not_acceptable', :via => :all
  match '410' => 'errors#gone', :via => :all
  match '500' => 'errors#internal_server_error', :via => :all
end

app/models/staff.rb
# frozen_string_literal: true

# Defines a staff, having relationship with Person(parent at database level), Job Title(role),
# Speciality, Team(Can be owner), others include join tables
#
# Implement Devise for authentication, using user id and password, and +active+ status
#
#
# @author Bereketab Gulai


# == Schema Information
#
# Table name: staffs
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  userId                 :string           not null
#  team_id                :bigint(8)        not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  active                 :boolean          default(FALSE), not null

class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable,
  # not using :registerable, instead custom staffs
  #
  # Registerable is disabled, there is custom controller for registering Staff
  #
  # Authentication keys changes the login identifier, userId, original email
  devise(:database_authenticatable, #:registerable,
         :recoverable, :trackable, :validatable, #:rememberable,
         :timeoutable, authentication_keys: [:userId])

  # Association to team is nullable/optional
  belongs_to(:team, optional: true)

  # Association with Person class, as polymorphic
  has_one(:person, as: :personalDetail, dependent: :destroy)

  # Setup many-to-many association through the corresponding join table
  # Through expects that junctions are declared
  has_many(:specialisms, dependent: :destroy)
  has_many(:jobs, dependent: :destroy)
  has_many(:specialities, through: :specialisms)
  has_many(:job_titles, through: :jobs)


  # For nested forms
  # Use for additional validations, reject_if: proc { |attributes| attributes[:attribute].blank? }
  accepts_nested_attributes_for(:specialisms, allow_destroy: true, update_only: true)
  accepts_nested_attributes_for(:jobs, allow_destroy: true, update_only: true)
  accepts_nested_attributes_for(:person, update_only: true, allow_destroy: true)


  validates_associated(:person)
  validates_associated(:specialisms)
  validates_associated(:jobs)
  validates(:userId, presence: true, uniqueness: { case_sensitive: true })

  # Provides access to the parent methods, or the class person, not working
  # delegate(:firstName, :lastName, to: :person, prefix: :pd)


  # Manage staff activity with these methods
  enum active: { active: true, inactive: false }

  # Gets the first job title of the staff
  #
  # @return [title:string]
  def role_name
    # First one only for now
    staff_job_titles[0]
  end

  # Job Titles as Roles
  #
  # @return [true/false:boolean]
  def medical_staff_admin?
    is_job?('Medical Records Staff')
  end

  # @return [true/false:boolean]
  def consultant?
    is_job?('Consultant')
  end

  # @return [true/false:boolean]
  def doctor?
    is_job?('Doctor')
  end

  # @return [true/false:boolean]
  def staff_nurse?
    is_job?('Staff Nurse')
  end

  # @return [true/false:boolean]
  def nurse?
    is_job?('Nurse')
  end

  # @return [true/false:boolean]
  def ward_sister?
    is_job?('Ward Sister')
  end

  # Method to only authenticated active staff
  #
  # @return [true/false:boolean]
  def active_for_authentication?
    # Uncomment the below debug statement to view the properties of the returned self model values.
    # logger.debug self.to_yaml

    # Add active condition to existing base
    super && active?
  end

  # Sets the timeout length for Devise TimeOutable
  #
  # @return [Time] In minutes (30)
  def timeout_in
    30.minutes
  end

  private

  # Checks if any of the passed in matches the job titles of this staff
  #
  # @param title the name of the job title
  #
  # @return [boolean]
  def is_job?(title)
    # Loop through the returned titles and return when true is found
    staff_job_titles.each do |current_title|
      return true if current_title.eql?(title)
    end

    # Otherwise return false
    false
  end

  # Gets the job titles of this staff
  #
  # @return [titles:array]
  def staff_job_titles
    # Only the title attribute
    job_titles.map(&:title)
  end
end

app/controllers/staffs_controller.rb
# Handles staff management system, to view, create and update
#
# @author Bereketab Gulai
class StaffsController < ApplicationController
  before_action(:set_staff, only: [:show, :edit, :update])

  # GETs staffs page
  def index
    authorize(:staff)
    @staffs = Staff.all
  end

  # GETs staff profile
  def show
  end

  # GETs registration page
  def new
    authorize(:staff)
    @staff = Staff.new
    @staff.build_person
    @staff.person.build_address
    @staff.specialisms.build
    @staff.jobs.build
  end

  # POSTs registration form to create staff
  def create
    authorize(:staff)
    @staff = Staff.new(staff_params)

    if @staff.save
      redirect_to(staffs_path, notice: 'Staff registration successful')
    else
      # Will take care of the format
      respond_with(@staff)
    end
  end

  # GETs edit form
  def edit
  end

  # POST method, uses edit form data to update staff
  def update
    authorize(:staff)

    # Remove the password from params so it does not updated if it is blank
    params[:staff].delete(:password) if params[:staff][:password].blank?
    params[:staff].delete(:password_confirmation) if params[:staff][:password_confirmation].blank?

    if @staff.update(staff_params)
      redirect_to(staffs_path, notice: 'Staff update successful')
    else
      # Will take care of the format
      respond_with(@staff)
    end
  end

  private

  # Permitted params
  def staff_params
    params.require(:staff).permit(:id, :userId, :team_id, :email, :password, :password_confirmation,
                                  person_attributes: [:id, :firstName, :lastName, :gender, :dateOfBirth, :telHomeNo, :telMobileNo,
                                                      address_attributes: [:id, :houseNumber, :street, :town, :postcode]],
                                  specialisms_attributes: [:id, :speciality_id],
                                  jobs_attributes: [:id, :job_title_id])
  end

  # Sets and authorises staff record
  def set_staff
    @staff = Staff.find(params[:id])

    # In this situation where staff can only access their profile unless admin
    # The record must be given, that is: @staff
    authorize(@staff)
  end
end

app/views/staffs/_form.html.erb
<div class="col-10" id="error_holder_staffs_new">
  <%= render('shared/errors', model: @staff) %>
</div>

<%= form_with(model: @staff, html: { autoComplete: :on }) do |staff_form| %>
  <table class="table borderless">
    <tbody>
    <tr>
      <td colspan="2">
        <%# Get the attributes that belong to the person class %>
        <%= staff_form.fields_for(:person) do |person_fields| %>
          <%= render('shared/personal_detail_fields', person_fields: person_fields, disabled: false) %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td style="width: 50%; !important;">
        <fieldset class="none-bs-fieldset">
          <legend class="none-bs-legend">Account Details</legend>
          <table class="table borderless">
            <tbody>
            <tr>
              <td>
                <div class="form-group">
                  <%= staff_form.label(:userId, 'User ID') %><br/>
                  <%= staff_form.text_field(:userId, autocomplete: 'off', required: true, class: 'form-control', disabled: (true if action_name == 'edit'), readOnly: (true if action_name == 'edit')) %>
                </div>
                <div class="form-group">
                  <%= staff_form.label(:email) %><br/>
                  <%= staff_form.email_field(:email, pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$", required: true, class: 'form-control') %>
                </div>
                <div class="form-group">
                  <%= staff_form.label(:password) %>
                  <% if @minimum_password_length %>
                    <em>(<%= @minimum_password_length %> characters minimum)</em>
                  <% end %><br/>
                  <%= staff_form.password_field(:password, required: (true unless action_name == 'edit'), class: 'form-control') %>
                </div>
              </td>
              <!--Override bootstrap td specifically here-->
              <td style="vertical-align: bottom; !important;">
                <div class="form-group">
                  <%= staff_form.label(:password_confirmation, 'Password confirmation') %><br/>
                  <%= staff_form.password_field(:password_confirmation, required: (true unless action_name == 'edit'), class: 'form-control') %>
                </div>
              </td>
              <td></td>
            </tr>
            </tbody>
          </table>
        </fieldset>
      </td>
      <td>
        <fieldset class="none-bs-fieldset">
          <legend class="none-bs-legend">Allocations</legend>
          <!--TODO finish this-->
          <table class="table borderless">
            <tbody>
            <tr>
              <%= staff_form.fields_for(:specialisms) do |specialism_fields| %>
                <td>
                  <div class="form-group">
                    <%= specialism_fields.label(:speciality_id, 'Speciality') %><br/>
                    <%= specialism_fields.select(:speciality_id, specialities_option, { include_blank: 'Select Speciality' }, required: true, class: 'form-control',
                                                 disabled: (true if action_name == 'edit'), readOnly: (true if action_name == 'edit')) %>
                  </div>
                </td>
              <% end %>
              <%= staff_form.fields_for(:jobs) do |job_fields| %>
                <td>
                  <div class="form-group">
                    <%= job_fields.label(:job_title_id, 'Job title') %><br/>
                    <%= job_fields.select(:job_title_id, job_titles_option, { include_blank: 'Select Job Title' }, required: true, class: 'form-control',
                                          disabled: (true if action_name == 'edit'), readOnly: (true if action_name == 'edit')) %>
                  </div>
                </td>
              <% end %>
            </tr>
            <tr>
              <td>
                <div class="form-group">
                  <%= staff_form.label(:team_id) %><br/>
                  <%= staff_form.select(:team_id, teams_option, { include_blank: 'Select Team' }, required: true, class: 'form-control',
                                        disabled: (true if action_name == 'edit'), readOnly: (true if action_name == 'edit')) %>
                </div>
              </td>
            </tr>
            </tbody>
          </table>
        </fieldset>
      </td>
    </tr>
    </tbody>
  </table>
  <div class="actions form-group">
    <table class="table borderless">
      <tbody>
      <tr>
        <td>  <%= staff_form.submit({ class: 'btn btn-primary' }) %></td>
      </tr>
      </tbody>
    </table>
  </div>
<% end %>

app/views/staffs/create.js.erb
//remove old validation messages
$(".alert").remove();

//display new validation messages
$('#error_holder_staffs_new').append('<%= escape_javascript(render('shared/errors', model: @staff))%>');

app/views/staffs/edit.html.erb
<h1>Edit Staff Profile</h1>
<% @page_title = 'Staff | Edit' %>
<%= render('form', staff: @staff)%>


app/views/staffs/index.html.erb
<% @page_title = 'Staff' %>

<h1>Staff</h1>

<br/>
<div class="row">
  <div class="col-1">
    <div class="btn-group mr-auto">
      <% disable_btn_export = @staffs.nil? || @staffs&.empty? ? 'disabled' : '' %>
      <%= link_to('Print', '#', onClick: "printJS({ printable: 'staffs_holder', type: 'html', header: 'Staff - #{localize(Date.today, format: :custom).to_s}', ignoreElements:['action']})",
                  class: "btn btn-outline-secondary #{disable_btn_export}") %>
    </div>
  </div>
</div>
<br/>
<div id="staffs_holder">
  <table class="table table-bordered table-striped">
    <thead class="thead-light">
    <tr>
      <th>Full Name</th>
      <th>User Id</th>
      <th>Speciality</th>
      <th>Job Title</th>
      <th>Active</th>
      <th id="action">Action</th>
    </tr>
    </thead>
    <tbody>

    <%# & symbol used as safe navigation or exits if object is null %>
    <% @staffs&.each do |staff| %>
      <tr>
        <td><%= staff.person.full_name %></td>
        <td><%= staff.userId %></td>
        <% staff&.specialities.each do |speciality| %>
          <td><%= speciality.speciality %></td>
        <% end %>
        <% staff&.job_titles.each do |job_title| %>
          <td><%= job_title.title %></td>
        <% end %>
        <td><%= staff.active %></td>
        <td id="action"><%= link_to('View Details', staff_path(staff), class: 'btn btn-secondary') %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% content_for(:navigationButtons) do %>
  <%= link_to('Register Staff', new_staff_path, class: 'btn btn-primary') if policy(:staff).new? %>
<% end %>

app/views/staffs/new.html.erb
<h1 class="title-container">Register New Staff</h1>
<% @page_title = 'Staff | Register' %>
<%= render('form', staff: @staff)%>

<% content_for(:navigationButtons) do %>
  <%= link_to 'Cancel', staffs_path, class: 'btn btn-secondary' %>
<% end %>

app/views/staffs/show.html.erb
<% @page_title = 'Staff | Profile' %>

<h1> <%= @staff.person.full_name %> </h1>
<br/>
<div class="row">
  <div class="col-1">
    <div class="btn-group mr-auto">
      <% disable_btn_export = @staff.nil? || @staff&.blank? ? 'disabled' : '' %>
      <%= link_to('Print', '#', onClick: "printJS({ printable: 'staff_holder', type: 'html', header: 'Staff #{
      @staff.person.full_name + ' ' + (localize(Date.today, format: :custom).to_s)}', ignoreElements:['action']})",
                  class: "btn btn-outline-secondary #{disable_btn_export}") %>
    </div>
  </div>
</div>
<br/>

<div id="staff_holder">
  <table class="table table-bordered table-striped">
    <thead class="thead-light">
    <tr>
      <th>ID No</th>
      <th>Date Of Birth</th>
      <th>Gender</th>
      <th>Address</th>
      <th>Email</th>
      <th>Home Telephone No</th>
      <th>Mobile Telephone No</th>
      <th>Register Date</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @staff.id %></td>
      <td><%= localize(@staff.person.dateOfBirth) %></td>
      <td><%= @staff.person.gender %></td>
      <%#	 binding.pry %>
      <td><%= @staff.person.full_address %></td>
      <td><%= @staff.email %></td>
      <td><%= @staff.person.telHomeNo %></td>
      <td><%= @staff.person.telMobileNo %></td>
      <td><%= localize(@staff.created_at.to_date) %></td>
    </tr>
    </tbody>
  </table>
  <br>
  <br>
  <h4>Specialism</h4>
  <table class="table table-bordered table-striped">
    <thead class="thead-light">
    <tr>
      <th>Speciality</th>
      <th>Date</th>
    </tr>
    </thead>
    <tbody>
    <% @staff.specialisms.each do |specialism| %>
      <tr>
        <td><%= specialism.speciality.speciality %></td>
        <td><%= localize(specialism.created_at.to_date) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>
  <br>
  <h4>Job Title</h4>
  <table class="table table-bordered table-striped">
    <thead class="thead-light">
    <tr>
      <th>Title</th>
      <th>Date</th>
    </tr>
    </thead>
    <tbody>
    <% @staff.jobs.each do |job| %>
      <tr>
        <td><%= job.job_title.title %></td>
        <td><%= localize(job.created_at.to_date) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<% content_for(:navigationButtons) do %>
  <% session[:staffs_show_back_url] = request.referrer if session[:staffs_show_back_url].nil? %>
  <%# Staff can only view their profile, therefore otherwise redirect to home when referrer is not available %>
  <%= link_to('Back', session[:staffs_show_back_url] || home_path, class: 'btn btn-secondary') %>
  &nbsp;
  <%= link_to('Edit', edit_staff_path(@staff), class: 'btn btn-secondary') if policy(:staff).update? %>
<% end %>


app/views/staffs/update.js.erb
//remove old validation messages
$("#error_explanation").remove();

//display new validation messages
$('#error_holder_staffs_new').append('<%= escape_javascript(render('shared/errors', model: @staff))%>');