config/routes.rb
# frozen_string_literal: true

# Main Router
Rails.application.routes.draw do
  namespace :reports do
    get :ward_list
    get :medications_list
    get :discharge_list
    get :patient_card
  end
  resource :invoice_payments
  resources :diagnoses
  resources :invoices do
    member do
      get :receive_payment
    end
    collection do
      post :set_payment_received
      # get :send_mail
    end
  end
  resources :wards do
    collection do
      match 'search' => 'wards#search', via: %i[get post], as: :search
    end
  end
  resources :drugs
  resources :patients
  resources :teams
  resources :treatments
  resources :prescriptions
  resources :staffs
  resources :specialities
  resources :job_titles
  resources :admissions do
    # Members require admission id
    member do
      get :discharge
      post :authorise_discharge
      patch :admit_scheduled
      delete :cancel_scheduled
    end
    # Collections do not require id
    collection do
      get :find_and_discharge
      match 'search' => 'admissions#search', via: %i[get post], as: :search
    end
  end

  # Find controller under search module and it is actions
  namespace :search do
    get :search, to: 'search#search', as: :search
    get 'find_admitted_patients_in_ward', to: 'find#find_admitted_patients_in_ward'
    get 'find_patients_discharge_unauthorised', to: 'find#find_patients_discharge_unauthorised'
    get 'find_discharged_without_invoice_patients_in_ward', to: 'find#find_discharged_without_invoice_patients_in_ward'
    get 'find_admitted_diagnosed_patients_in_ward', to: 'find#find_admitted_diagnosed_patients_in_ward'
  end

  # Change devise routes from staffs/login to /login
  devise_for :staffs, path: '',
             path_names: { sign_in: 'login', account_update: 'update' }

  # On the scope of devise, manage authenticated and unauthenticated users
  devise_scope :staff do
    authenticated :staff do
      root to: 'home#index'
    end
    unauthenticated :staff do
      root to: 'devise/sessions#new'
    end
  end

  get :home, to: 'home#index'

  root to: 'devise/sessions#new'

  # Handle errors, must be at end
  # Tell Router how to handle error by matching status code
  match '404' => 'errors#not_found', :via => :all
  match '406' => 'errors#not_acceptable', :via => :all
  match '410' => 'errors#gone', :via => :all
  match '500' => 'errors#internal_server_error', :via => :all
end

app/models/treatment.rb
# Model modified to be considered as notes holder for a patient during their admission
#
# @note name still kept to reserve the requirement, should take change in future maintenance
#
# @author Bereketab Gulai

# == Schema Information
#
# Table name: treatments
#
#  id           :bigint(8)        not null, primary key
#  date         :date
#  note         :text
#  issuedBy     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  admission_id :bigint(8)
#

# TODO Name of treatment requires changing
class Treatment < ApplicationRecord
  belongs_to :admission
  has_one(:patient, through: :admission)

  validates(:note, presence: true)
end

app/controllers/treatments_controller.rb
# Handles treatement/notes system, to view, create and update
#
# @author Bereketab Gulai
class TreatmentsController < ApplicationController
  before_action(:set_treatment, only: [:show, :edit, :update, :destroy])

  # GETs all notes
  def index
    authorize(:treatment)
    @treatments = Treatment.all
  end

  # GETs individual note
  def show
  end

  # GETs create note form
  def new
    authorize(:treatment)
    @treatment = Treatment.new

    if params.include?(:ward_id) && params.include?(:patient_id) && @admission.eql?(nil)
      admission_id_extract = params[:patient_id].split('|')[1]
      @admission = Admission.find(admission_id_extract)

    elsif params.include?(:rest_patient)
      @admission = nil
    end
  end

  # POSTs note creation
  def create
    authorize(:treatment)
    @treatment = Treatment.new(treatment_params)

    if @treatment.save
      redirect_to(treatments_path, notice: 'Note was successfully created')
    else
      respond_with(@treatment)
    end
  end

  # GETs edit form
  def edit
  end

  # POST method, receives edit form to create note
  def update
    if @treatment.update(treatment_params)
      redirect_to(treatments_path, notice: 'Note was successfully updated')
    else
      respond_with(:create)
    end
  end

  # DELETE method to destroy
  def destroy
    @treatment.destroy
    redirect_to(treatments_path, notice: 'Note was successfully deleted')
  end

  private

  # Permitted params
  def treatment_params
    params.require(:treatment).permit(:id, :note, :date, :issuedBy, :ward_id, :admission_id, :rest_patient)
  end

  # Authorises and sets note
  def set_treatment
    authorize(:treatment)
    @treatment = Treatment.find(params[:id])
  end

end

app/views/treatments/_form.html.erb
<div class="col-10" id="error_holder_note">
  <%= render('shared/errors', model: treatment) %>
</div>

<% staff = Staff.find_by(userId: treatment.issuedBy) if treatment.issuedBy %>

<%= form_with(model: treatment, validate: true) do |treatment_form| %>
  <%= treatment_form.hidden_field(:admission_id, value: treatment&.admission&.id||(admission&.id if admission)  ) %>
  <%= treatment_form.hidden_field(:date, value: treatment.date || Date.today) %>
  <%#	 Helper method %>
  <%= treatment_form.hidden_field(:issuedBy, value: (treatment.issuedBy) || current_staff.userId) %>
  <table class="table borderless">
    <tbody>
    <tr>
      <td>
        <div class="form-group">
          <%= treatment_form.label(:note) %><br/>
          <%= treatment_form.text_area(:note, class: 'form-control', required: true) %>
        </div>
      </td>
      <td>
        <div class="form-group">
          <%= treatment_form.label(:date) %><br/>
          <%= treatment_form.label(:date, localize(Date.today)) %>
        </div>
      </td>
      <td>
        <div class="form-group">
          <%= treatment_form.label(:issuedBy, 'Issued By') %><br/>
          <%#	Use the saved staff or go for new if it is null/initialised state %>
          <%= treatment_form.label(:issuedBy, (person_full_name_helper(staff) if staff) || person_full_name_helper(current_staff)) %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="form-group">
          <%= treatment_form.submit(class: 'btn btn-primary') %>
        </div>
      </td>
    </tr>
    </tbody>
  </table>
<% end %>

app/views/treatments/create.js.erb
// Remove old validation messages
$(".alert").remove();

// Display new validation messages
$('#error_holder_note').append('<%= escape_javascript(render('shared/errors', model: @treatment))%>');

app/views/treatments/edit.html.erb
<% @page_title = 'Notes | Update Note' %>

<% patient = @treatment.patient %>
<h1>Note update for <%= person_full_name_helper(patient) %></h1>
<%= render 'form', treatment: @treatment, patient: patient%>

<% content_for(:navigationButtons) do %>
  <%= link_to 'Cancel', treatments_path, class: 'btn btn-secondary' %>
<% end %>

app/views/treatments/index.html.erb
<h1 class="title-container">Notes</h1>
<% @page_title = 'Notes' %>
<br/>
<div class="row">
  <div class="col-1">
    <div class="btn-group mr-auto">
      <% disable_btn_export = @treatments.nil? || @treatments&.empty? ? 'disabled' : '' %>
      <%= link_to('Print', '#', onClick: "printJS({ printable: 'notes_holder_index', type: 'html', header: 'Notes - #{localize(Date.today, format: :custom).to_s}', ignoreElements:['action']})",
                  class: "btn btn-outline-secondary #{disable_btn_export}") %>
      <%#link_to('Export as Excel', admissions_path(format: :xlsx), { class: "btn btn-outline-secondary form-control #{disable_btn_export}",
                                                                       role: 'button' }) %>
    </div>
  </div>
</div>
<br/>

<table class="table table-bordered table-striped" id="notes_holder_index">
  <thead class="thead-light">
  <tr>
    <th>Note Date</th>
    <th>Note No</th>
    <th>Patient Name</th>
    <th>Issued By</th>
    <th id="action">Action</th>
  </tr>
  </thead>
  <tbody>
  <% if @treatments && !@treatments&.empty? %>
    <% @treatments&.each do |treatment| %>
      <% patient = treatment.patient %>
      <% staff = Staff.find_by(userId: treatment.issuedBy) %>
      <tr>
        <td><%= localize(treatment.date) %> </td>
        <td><%= treatment.id %></td>
        <td><%= person_full_name_helper(patient) if patient %></td>
        <td><%= person_full_name_helper(staff) if staff %></td>
        <td id="action">
          <%= link_to('View', treatment_path(treatment.id), role: 'button', class: 'btn btn-secondary') %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="5"><p>No notes found.</p></td>
    </tr>
  <% end %>
  </tbody>
</table>


<% content_for(:navigationButtons) do %>
  <%= link_to('Make Note', new_treatment_path, class: 'btn btn-primary') if policy(:treatment).new? %>
<% end %>

app/views/treatments/new.html.erb
<h1>Make Note</h1>
<% @page_title = 'Notes | Make Note' %>

<% if @admission %>
  <fieldset class="none-bs-fieldset">
    <legend class="none-bs-legend">Patient Details</legend>
    <%= render 'patients/form', patient: @admission.patient %>
  </fieldset>
  <fieldset class="none-bs-fieldset">
    <legend class="none-bs-legend">Note</legend>
    <%= render 'form', treatment: @treatment, admission: @admission %>
  </fieldset>
<% else %>
  <%= render 'shared/find_admitted_patient', action_controller_url: new_treatment_path %>
<% end %>

<% content_for(:navigationButtons) do %>
  <%= link_to 'Cancel', treatments_path, class: 'btn btn-secondary' %>
<% end %>

app/views/treatments/show.html.erb
<% patient = @treatment.admission.patient %>
<h1 class="title-container">Note for <%= (person_full_name_helper(patient) if patient) %></h1>
<br/>
<div class="row">
  <div class="col-1">
    <div class="btn-group mr-auto">
      <% disable_btn_export = @admissions.nil? || @admissions&.empty? ? 'disabled' : '' %>
      <%= link_to('Print', '#', onClick: "printJS({ printable: 'note_holder', type: 'html', header: 'Note for #{((person_full_name_helper(patient) if patient) || '') + ', ' + localize(Date.today, format: :custom).to_s}'})",
                  class: "btn btn-outline-secondary #{disable_btn_export}") %>
    </div>
  </div>
</div>
<br/>

<table class="table table-bordered table-striped " id="note_holder">
  <thead class="thead-light">
  <tr>
    <th>Note Date</th>
    <th>Note No</th>
    <th>Issued By</th>
    <th colspan="2">Action</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>
      <%= localize(@treatment.date) %>
    </td>
    <td>
      <%= @treatment.id %>
    </td>
    <td>
      <%= person_full_name_helper(Staff.find_by(userId: @treatment.issuedBy)) %>
    </td>
    <% if policy(:treatment).update? %>
      <td>
        <%= link_to('Edit', edit_treatment_path(@treatment.id), role: 'button', class: 'btn btn-secondary') %>
      </td>
      <td>
        <%= link_to('Delete', treatment_path(@treatment.id), method: :delete, data: { confirm: "Should this Note no. #{@treatment.id} be deleted?" }, role: 'button', class: 'btn btn-secondary') %>
      </td>
    <% end %>
  </tr>
  <tr>
    <th>Notes</th>
  </tr>
  <tr>
    <td><p><%= @treatment.note %></p></td>
  </tr>
  </tbody>
</table>

<%= content_for(:navigationButtons) do %>
  <%= link_to('Back', treatments_path, role: 'button', class: 'btn btn-primary') %>
<% end %>