config/routes.rb
# frozen_string_literal: true

# Main Router
Rails.application.routes.draw do
  namespace :reports do
    get :ward_list
    get :medications_list
    get :discharge_list
    get :patient_card
  end
  resource :invoice_payments
  resources :diagnoses
  resources :invoices do
    member do
      get :receive_payment
    end
    collection do
      post :set_payment_received
      # get :send_mail
    end
  end
  resources :wards do
    collection do
      match 'search' => 'wards#search', via: %i[get post], as: :search
    end
  end
  resources :drugs
  resources :patients
  resources :teams
  resources :treatments
  resources :prescriptions
  resources :staffs
  resources :specialities
  resources :job_titles
  resources :admissions do
    # Members require admission id
    member do
      get :discharge
      post :authorise_discharge
      patch :admit_scheduled
      delete :cancel_scheduled
    end
    # Collections do not require id
    collection do
      get :find_and_discharge
      match 'search' => 'admissions#search', via: %i[get post], as: :search
    end
  end

  # Find controller under search module and it is actions
  namespace :search do
    get :search, to: 'search#search', as: :search
    get 'find_admitted_patients_in_ward', to: 'find#find_admitted_patients_in_ward'
    get 'find_patients_discharge_unauthorised', to: 'find#find_patients_discharge_unauthorised'
    get 'find_discharged_without_invoice_patients_in_ward', to: 'find#find_discharged_without_invoice_patients_in_ward'
    get 'find_admitted_diagnosed_patients_in_ward', to: 'find#find_admitted_diagnosed_patients_in_ward'
  end

  # Change devise routes from staffs/login to /login
  devise_for :staffs, path: '',
             path_names: { sign_in: 'login', account_update: 'update' }

  # On the scope of devise, manage authenticated and unauthenticated users
  devise_scope :staff do
    authenticated :staff do
      root to: 'home#index'
    end
    unauthenticated :staff do
      root to: 'devise/sessions#new'
    end
  end

  get :home, to: 'home#index'

  root to: 'devise/sessions#new'

  # Handle errors, must be at end
  # Tell Router how to handle error by matching status code
  match '404' => 'errors#not_found', :via => :all
  match '406' => 'errors#not_acceptable', :via => :all
  match '410' => 'errors#gone', :via => :all
  match '500' => 'errors#internal_server_error', :via => :all
end

app/models/prescription.rb
# Allows to make diagnosis prescription
#
# @author Bereketab Gulai

# == Schema Information
#
# Table name: prescriptions
#
#  id              :bigint(8)        not null, primary key
#  date            :date
#  dosage          :string
#  treatmentLength :integer
#  issuedBy        :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  diagnosis_id    :bigint(8)
#

class Prescription < ApplicationRecord
  belongs_to :diagnosis
  has_many(:medications, dependent: :destroy)
  has_many(:drugs, through: :medications, dependent: :destroy)

  accepts_nested_attributes_for(:medications, allow_destroy: true)

  human_attribute_name(:treatmentLength)
  human_attribute_name(:issuedBy)

  # Validates all fields
  validates(:date, presence: true)
  validates(:dosage, presence: true)
  validates(:treatmentLength, presence: true)
  validates(:issuedBy, presence: true)
end

app/controllers/prescriptions_controller.rb
# Prescriptions Controller, manages all drup prescriptions requests, index, creation, deletion and more
#
# @author Bereketab Gulai
class PrescriptionsController < ApplicationController
  before_action(:set_prescription, only: [:show, :edit, :update, :destroy])


  def index
    # Needs to know the policy, which is of prescription
    authorize(:prescription)
    @prescriptions = Prescription.all
  end

  def show
  end

  def new
    authorize(:prescription)
    @prescription = Prescription.new
    @prescription.medications.build

    if params.include?(:ward_id) && params.include?(:patient_id) && @patient.eql?(nil)
      admission_id_extract = params[:patient_id].split('|')[1]
      @diagnosis = Diagnosis.find_by(admission_id: admission_id_extract)

      # Save the admission to session and use it if re-rendering is required (create errors)
      session[:current_prescribing_diagnosis] = @diagnosis
    elsif params.include?(:rest_patient)
      @diagnosis = nil
    end
  end

  def create
    authorize(:prescription)
    @prescription = Prescription.new(prescription_params)

    if @prescription.save
      redirect_to(prescriptions_path, notice: 'Prescription created successfully')
    end
  end

  def edit
  end

  def update
    if @prescription.update(prescription_params)
      redirect_to(prescriptions_path, notice: 'Update successful')
    else
      respond_with(:edit)
    end
  end

  # Optimize Nothing should be deleted
  def destroy
    # @prescription.destroy
    # redirect_to :index, notice: 'Prescription Deleted'
  end

  # Private methods
  private

  # @return [params]
  def prescription_params
    params.require(:prescription).permit(:id, :date, :dosage, :treatmentLength, :issuedBy, :diagnosis_id,
                                         :ward_id, :patient_id, medications_attributes: [:id, :drug_id, :_destroy])
  end


  # @return [admission]
  def set_prescription
    authorize(:prescription)
    @prescription = Prescription.find(params[:id])
  end
end

app/helpers/prescriptions_helper.rb
# Helper for prescriptions views
#
# @author Bereketab Gulai
module PrescriptionsHelper

  # Drug options
  # OPTIMIZE requires fixing
  def drug_options
    # Remove the drugs which cannot be used again for today
    if !@diagnosis.prescriptions.all.empty?
      @diagnosis.prescriptions.all.each_with_index do |p, index|
        # binding.pry
        if p.date == Date.today
          # Return all the drugs excluding the drugs used this day,
          # Map them to name as key and id as value, limit to 10
          return Drug.where.not(id: p.drugs).all.limit(10).map do |drug|
            [drug.name, drug.id]
          end
        elsif index == @patient.prescriptions.all.size - 1
          return get_all_drugs
        end
      end
    else
      get_all_drugs
    end
  end

  private

  # All drugs
  #
  # @return [[Array]] - name - id
  def get_all_drugs
    # Otherwise return all, limit to 10
    Drug.all.limit(10).map do |drug|
      [drug.name, drug.id]
    end
  end
end

app/views/prescriptions/_form.html.erb
<%= render 'shared/errors', model: prescription %>
<%= form_with(model: prescription, validate: true) do |prescription_form| %>
  <%= prescription_form.hidden_field(:diagnosis_id, value: prescription.diagnosis_id || diagnose.id) %>
  <%= prescription_form.hidden_field(:date, value: prescription.date || Date.today) %>
  <%= prescription_form.hidden_field(:issuedBy, value: prescription.issuedBy || current_staff.userId) %>
  <div class="row">
    <div class="col offset-1">
      <div class="row">
        <%= prescription_form.fields_for(:medications) do |medication_field| %>
          <div class="drugs col-6">
            <%= render('medication_fields', f: medication_field) %>
          </div>
        <% end %>
        <div class="col-5">
          <div class="row">
            <div class="col-6">
              <div class="form-group">
                <%= prescription_form.label(:dosage) %><br/>
                <%= prescription_form.text_area(:dosage, required: true, class: 'form-control') %>
              </div>
            </div>
            <div class="col-6">
              <div class="form-group">
                <%= prescription_form.label(:treatmentLength) %><br/>
                <%= prescription_form.text_field(:treatmentLength, type: 'number', required: true, class: 'form-control') %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= prescription_form.label(:date) %><br/>
                <%= prescription_form.label(:date, localize(Date.today)) %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <%= prescription_form.label(:issuedBy) %><br/>
                <%= prescription_form.label(:issuedBy, (person_full_name_helper(Staff.find_by(userId: prescription.issuedBy)) if prescription.issuedBy) || person_full_name_helper(current_staff)) %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br/>
      <br/>
      <div class="row">

        <div class="col-2 offset-6">
          <%= link_to_add_association('Add drug', prescription_form, :medications, class: 'btn btn-primary',
                                      data: { association_insertion_node: '.drugs', association_insertion_method: :append }) %>
        </div>
        <div class="col-2 offset-1">
          <div class="form-group">
            <%= prescription_form.submit(class: 'btn btn-primary') %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/prescriptions/_medication_fields.html.erb
<div class="nested_fields row">
  <div class="col-8">
    <div class="form-group">
      <%= f.label(:drug_id, 'Drug Name') %><br/>
      <%= f.select(:drug_id, drug_options, { include_blank: 'Select drug' }, { id: 'drug_select', required: true, class: 'form-control' }) %>
    </div>
  </div>

  <div class="col" style="padding-top: 0.5rem;">
    <br/>
    <div class="form-group">
      <%= link_to_remove_association('Remove Drug', f, class: 'form-control btn btn-danger') %>
    </div>
  </div>
</div>

app/views/prescriptions/edit.html.erb
<% patient = @prescription.patient %>
<h1 class="title-container">Prescription Update for <%= person_full_name_helper(patient) %></h1>
<%= render('form', prescription: @prescription, patient: patient) %>

app/views/prescriptions/index.html.erb
<h1 class="title-container">Prescriptions</h1>
<% @page_title = 'Prescriptions' %>
<br/>
<div class="row">
  <div class="col-1">
    <div class="btn-group mr-auto">
      <% disable_btn_export = @prescriptions.nil? || @prescriptions&.empty? ? 'disabled' : '' %>
      <%= link_to('Print', '#', onClick: "printJS({ printable: 'prescriptions_holder_index', type: 'html', header: 'Prescriptions - #{localize(Date.today, format: :custom).to_s}'})",
                  class: "btn btn-outline-secondary #{disable_btn_export}") %>
      <%#link_to('Export as Excel', admissions_path(format: :xlsx), { class: "btn btn-outline-secondary form-control #{disable_btn_export}",
                                                                       role: 'button' }) %>
    </div>
  </div>
</div>
<br/>

<table class="table table-bordered table-striped" id="prescriptions_holder_index">
  <thead class="thead-light">
  <tr>
    <th>Prescription Date</th>
    <th>Prescription No</th>
    <th>Patient Name</th>
    <th>Issued By</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% if @prescriptions && !@prescriptions&.empty? %>
    <% @prescriptions&.each do |prescription| %>
      <% patient = prescription.diagnosis.patient if prescription.diagnosis %>
      <% staff = Staff.find_by(userId: prescription.issuedBy) %>
      <tr>
        <td><%= localize(prescription.date) %></td>
        <td><%= prescription.id %></td>
        <td><%= person_full_name_helper(patient) if patient %></td>
        <td><%= person_full_name_helper(staff) %></td>
        <td>
          <%= link_to('View', prescription_path(prescription.id), role: 'button', class: 'btn btn-secondary') %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="5"><p>No drug prescriptions found.</p></td>
    </tr>
  <% end %>
  </tbody>
</table>

<% content_for(:navigationButtons) do %>
  <%= link_to('Prescribe Drug', new_prescription_path, class: 'btn btn-primary') if policy(:prescription).new? %>
<% end %>

app/views/prescriptions/new.html.erb
<h1 class="title-container">Prescribe Drugs</h1>
<%	 @page_title = 'Prescribe Drugs' %>
<% if @diagnosis %>
  <fieldset class="none-bs-fieldset">
    <legend class="none-bs-legend">Patient Details</legend>
    <div class="patient_details_holder">
      <%= render 'patients/form', patient: @diagnosis.patient %>
    </div>
  </fieldset>
  <fieldset class="none-bs-fieldset">
    <legend class="none-bs-legend">Drug Prescription</legend>
    <div class="prescription_form_holder">
      <%= render 'form', prescription: @prescription, diagnose: @diagnosis %>
    </div>
  </fieldset>
<% else %>
  <%= render 'shared/find_diagnosed_patient', action_controller_url: new_prescription_path %>
<% end %>

<% content_for(:navigationButtons) do %>
  <%= link_to('Cancel', request.original_url || prescriptions_path, role: 'button', class: 'btn btn-secondary') %>
<% end %>

app/views/prescriptions/show.html.erb
<% patient = @prescription.diagnosis.patient if @prescription.diagnosis %>
<% staff = Staff.find_by(userId: @prescription.issuedBy) %>
<h1 class="title-container">Prescription for <%= person_full_name_helper(patient) if patient %></h1>
<br/>
<div class="row">
  <div class="col-1">
    <div class="btn-group mr-auto">
      <% disable_btn_export = @prescription.nil? || @prescription&.blank? ? 'disabled' : '' %>
      <%= link_to('Print', '#', onClick: "printJS({ printable: 'prescription_holder', type: 'html', header: 'Prescription for #{((person_full_name_helper(patient) if patient) || '' ) + ', ' +  localize(Date.today, format: :custom).to_s}'})",
                  class: "btn btn-outline-secondary #{disable_btn_export}") %>
    </div>
  </div>
</div>
<br/>

<div id="prescription_holder">
  <table class="table table-bordered table-striped">
    <thead class="thead-light">
    <tr>
      <th>Prescription Date</th>
      <th>Prescription No</th>
      <th>Length of Treatment</th>
      <th>Issued By</th>
      <!--<th colspan="2">Action</th>-->
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= localize(@prescription.date) %></td>
      <td><%= @prescription.id %></td>
      <td><p><%= @prescription.treatmentLength %></p></td>
      <td><%= person_full_name_helper(staff) if staff %></td>
      <!--<td>      -->
        <%# link_to('Edit', edit_prescription_path(@prescription.id), role: 'button', class: 'btn btn-secondary') if  %>
      <!--</td>-->
      <!--<td>     -->
        <%# link_to('Delete', prescription_path(@prescription.id), method: :delete, data: { confirm: "Should this prescription no. #{@prescription.id} be deleted?" }, role: 'button', class: 'btn btn-secondary') %>
      <!--</td>-->
    </tr>
    </tbody>
  </table>
  <br/>
  <br/>
  <h6>Drugs</h6>
  <table class="table table-bordered table-striped">
    <thead class="thead-light">
    <tr>
      <th>Drug Code</th>
      <th>Drug Name</th>
    </tr>
    </thead>
    <tbody>
    <% @prescription.drugs.each do |drug| %>
      <tr>
        <td> <%= drug.code %> </td>
        <td> <%= drug.name %> </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br/>
  <br/>
  <h6>Dosage</h6>
  <table class="table table-bordered table-striped">
    <thead class="thead-light">
    <tr>
      <th>Dosage</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><p><%= @prescription.dosage %></p></td>
    </tr>
    </tbody>
  </table>
</div>
<%= content_for(:navigationButtons) do %>
  <%= link_to('Back', prescriptions_path, role: 'button', class: 'btn btn-primary') %>
<% end %>