config/routes.rb
# frozen_string_literal: true

# Main Router
Rails.application.routes.draw do
  namespace :reports do
    get :ward_list
    get :medications_list
    get :discharge_list
    get :patient_card
  end
  resource :invoice_payments
  resources :diagnoses
  resources :invoices do
    member do
      get :receive_payment
    end
    collection do
      post :set_payment_received
      # get :send_mail
    end
  end
  resources :wards do
    collection do
      match 'search' => 'wards#search', via: %i[get post], as: :search
    end
  end
  resources :drugs
  resources :patients
  resources :teams
  resources :treatments
  resources :prescriptions
  resources :staffs
  resources :specialities
  resources :job_titles
  resources :admissions do
    # Members require admission id
    member do
      get :discharge
      post :authorise_discharge
      patch :admit_scheduled
      delete :cancel_scheduled
    end
    # Collections do not require id
    collection do
      get :find_and_discharge
      match 'search' => 'admissions#search', via: %i[get post], as: :search
    end
  end

  # Find controller under search module and it is actions
  namespace :search do
    get :search, to: 'search#search', as: :search
    get 'find_admitted_patients_in_ward', to: 'find#find_admitted_patients_in_ward'
    get 'find_patients_discharge_unauthorised', to: 'find#find_patients_discharge_unauthorised'
    get 'find_discharged_without_invoice_patients_in_ward', to: 'find#find_discharged_without_invoice_patients_in_ward'
    get 'find_admitted_diagnosed_patients_in_ward', to: 'find#find_admitted_diagnosed_patients_in_ward'
  end

  # Change devise routes from staffs/login to /login
  devise_for :staffs, path: '',
             path_names: { sign_in: 'login', account_update: 'update' }

  # On the scope of devise, manage authenticated and unauthenticated users
  devise_scope :staff do
    authenticated :staff do
      root to: 'home#index'
    end
    unauthenticated :staff do
      root to: 'devise/sessions#new'
    end
  end

  get :home, to: 'home#index'

  root to: 'devise/sessions#new'

  # Handle errors, must be at end
  # Tell Router how to handle error by matching status code
  match '404' => 'errors#not_found', :via => :all
  match '406' => 'errors#not_acceptable', :via => :all
  match '410' => 'errors#gone', :via => :all
  match '500' => 'errors#internal_server_error', :via => :all
end

app/views/shared/_errors.html.erb
<% if model&.errors&.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h4><%= pluralize(model.errors.count, 'error') %> prohibited this <%= (model.class).to_s.downcase %> from being saved:</h4>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message.humanize %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_find_admitted_patient.html.erb
<%# Local disables remote/ajax request so it reload the page %>
<fieldset class="none-bs-fieldset" style="width: 70%; !important;">
  <%= form_with(name: nil, url: action_controller_url, method: :get, local: true) do |form| %>
    <table class="table borderless">
      <tbody>
      <tr>
        <td class="form-group">
          <label>Ward</label><br/>
          <%# TODO add date range, to all date types %>
          <% %>
          <%= form.select(:ward_id, wards_option('wards_for_current_staff'), { include_blank: 'Select patient admission ward' }, { id: 'ward_id_select_find_admitted', required: true, class: 'form-control' }) %>
        </td>
        <td class="form-group">
          <label>Patient</label><br/>
          <%= form.select(:patient_id, {}, { include_blank: 'Select patient' }, { id: 'patient_id_select', disabled: true, required: true, class: 'form-control' }) %>
          <br/>
        </td>
      </tr>
      <tr>
        <td>
          <%#   %>
          <%= form.submit('Find',  {class: 'btn btn-primary', id: 'btn_submit_find_admitted', data: { disable_with: false }, disabled: true }) %>
        </td>
      </tr>
      </tbody>
    </table>
  <% end %>
</fieldset>

app/views/shared/_find_diagnosed_patient.html.erb
<%# Local disables remote/ajax request so it reload the page %>
<fieldset class="none-bs-fieldset" style="width: 70%; !important;">
  <%= form_with(name: nil, url: action_controller_url, method: :get, local: true) do |form| %>
    <table class="table borderless">
      <tbody>
      <tr>
        <td class="form-group">
          <label>Ward</label><br/>
          <%# TODO add date range, to all date types %>
          <% %>
          <%= form.select(:ward_id, wards_option('wards_for_current_staff'), { include_blank: 'Select patient admission ward' }, { id: 'ward_id_select_find_admitted', required: true, class: 'form-control' }) %>
        </td>
        <td class="form-group">
          <label>Patient</label><br/>
          <%= form.select(:patient_id, {}, { include_blank: 'Select patient' }, { id: 'patient_id_select_find_diagnosed', disabled: true, required: true, class: 'form-control' }) %>
          <br/>
        </td>
        <td class="form-group">
          <label>Diagnosis</label><br/>
          <%= form.select(:diagnosis_id, {}, { include_blank: 'Select Diagnosis' }, { id: 'diagnosis_id_select', disabled: true, required: true, class: 'form-control' }) %>
          <br/>
        </td>
      </tr>
      <tr>
        <td>
          <%#   %>
          <%= form.submit('Find', class: 'btn btn-primary', id: 'btn_submit_find_diagnosed', data: { disable_with: false }, disabled: true) %>
        </td>
      </tr>
      </tbody>
    </table>
  <% end %>
</fieldset>

app/views/shared/_find_discharged_patient.html.erb
<fieldset class="none-bs-fieldset" style="width: 70%; !important;">
<%# Local disables remote/ajax request so it reload the page %>
  <%= form_with(name: nil, url: action_controller_url, method: :get, local: true) do |form| %>
    <table class="table borderless">
      <tbody>
      <tr>
        <td>
          <label>Ward</label><br/>
          <%# TODO add date range, to all date types %>
          <% %>
          <%= form.select(:ward_id, wards_option, { include_blank: 'Select patient admission ward' }, { id: 'ward_id_select_find_discharged', required: true, class: 'form-control' }) %>
        </td>
        <td>
          <label>Patient</label><br/>
          <%= form.select(:patient_id, {}, { include_blank: 'Select patient' }, { id: 'patient_id_select', disabled: true, required: true, class: 'form-control' }) %>
          <br/>
        </td>
      </tr>
      <tr>
        <td>
          <%#   %>
          <%= form.submit('Find', class: 'btn btn-primary', id: 'btn_submit_find_discharged', data: { disable_with: false }, disabled: true) %>
        </td>
      </tr>
      </tbody>
    </table>
  <% end %>
</fieldset>

app/views/shared/_personal_detail_fields.html.erb
<fieldset class="none-bs-fieldset">
  <legend class="none-bs-legend">Personal Details</legend>
  <table class="table">
    <tbody>
    <tr>
      <td>
        <div class="form-group">
          <%= person_fields.label(:firstName, 'First name') %><br/>
          <%= person_fields.text_field(:firstName, { autofocus: true, class: 'form-control', required: true, disabled: (disabled if disabled) }) %>
        </div>
      </td>
      <td>
        <div class="form-group">
          <%= person_fields.label(:lastName, 'Last name') %><br/>
          <%= person_fields.text_field(:lastName, class: 'form-control', required: true, disabled: disabled) %>
        </div>
      </td>
      <td>
        <div class="form-group">
          <%= person_fields.label(:dateOfBirth, 'Date of birth') %><br/>
          <%= person_fields.text_field(:dateOfBirth, { type: 'date', min: '1900-01-01', max: Date.today.to_s, required: true, class: 'form-control', disabled: (disabled if disabled) }) %>
        </div>
      </td>
      <td>
        <div class="form-group">
          <%= person_fields.label(:gender) %><br/>
          <%= person_fields.select(:gender, options_for_select([:Male, :Female], selected: person_fields.object.gender), { include_blank: 'Select gender' }, { class: 'form-control', required: true, disabled: (disabled if disabled) }) %>
        </div>
      </td>
    </tr>
    <tr>
      <%= person_fields.fields_for(:address) do |address_fields| %>
        <td>
          <div class="form-group">
            <%= address_fields.label(:houseNumber, 'House number') %><br/>
            <%= address_fields.text_field(:houseNumber, { class: 'form-control', required: true, disabled: (disabled if disabled) }) %>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= address_fields.label :street %><br/>
            <%= address_fields.text_field(:street, class: 'form-control', required: true, disabled: (disabled if disabled)) %>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= address_fields.label(:town) %><br/>
            <%= address_fields.text_field(:town, class: 'form-control', required: true, disabled: (disabled if disabled)) %>

          </div>
        </td>
        <td>
          <div class="form-group">
            <%= address_fields.label(:postcode) %><br/>
            <%= address_fields.text_field(:postcode, { class: 'form-control', required: true, disabled: (disabled if disabled) }) %>
          </div>
        </td>
      <% end %>
    </tr>
    <tr>
      <td>
        <div class="form-group">
          <%= person_fields.label(:telHomeNo, 'Telephone number') %><br/>
          <%# min/max length not working %>
          <%= person_fields.text_field(:telHomeNo, type: 'number', class: 'form-control', minLength:'11', maxLength:'14', required: true, disabled: (disabled if disabled)) %>
        </div>
      </td>
      <td>
        <div class="form-group">
          <%= person_fields.label(:telMobileNo, 'Mobile number') %><br/>
          <%= person_fields.text_field(:telMobileNo, type: 'number', minLength:'11', maxLength:'14', class: 'form-control', disabled: (disabled if disabled)) %>
        </div>
      </td>
    </tr>
    </tbody>
  </table>
</fieldset>

app/views/shared/_side_nav.html.erb
<div class="sidebar bg-dark ">
  <div class="sidebar-toggle-holder" style="padding: 18px;">
    <a class="sidebar-toggle text-light">
      <i class="fas fa-bars fa-2x"></i>
    </a>
  </div>
  <br/>
  <br/>
  <br/>
  <!--TODO do dropright when toggled with jquery-->
  <ul class="list-unstyled main-side-list">
    <li>
      <a href="/"><i class="fas fa-home fa-2x custom_width_1_3em"></i><label class='lbl-nav col-sm-auto'>Home</label></a>
    </li>

    <li class="admission-side-menu">
      <a href="#submenu1" data-toggle="collapse"><i class="fas fa-address-card fa-2x custom_width_1_3em"></i><label class='lbl-nav col-sm-auto'>
        Admission </label></a>
      <ul id="submenu1" class="list-unstyled collapse">
        <li><%= link_to('View All', admissions_path, class: 'admission-side-menu') %></li>
        <% if policy(:admission).new? %>
          <li><%= link_to('Admit Patient', new_admission_path) %></li>
        <% end %>
        <% if policy(:admission).find_and_discharge? %>
          <li><%= link_to('Find and Discharge', find_and_discharge_admissions_path) %></li>
        <% end %>

      </ul>
    </li>
    <li class="treatment-side-menu">
      <a href="#submenu2" data-toggle="collapse"><i class="fas fa-file-medical fa-2x custom_width_1_3em"></i><label class='lbl-nav col-sm-auto'>
        Treatment </label></a>
      <ul id="submenu2" class="list-unstyled collapse">
        <li class="text-light">&nbsp;&nbsp;Diagnosis</li>
        <li><a href="/diagnoses">View All</a></li>
        <% if policy(:diagnoses).new? %>
          <li><a href="/diagnoses/new">Diagnose</a></li>
        <% end %>
        <li class="text-light">&nbsp;&nbsp;Drugs</li>
        <li><a href="/prescriptions">View all</a></li>
        <% if policy(:prescription).new? %>
          <li><a href="/prescriptions/new">Prescribe Drug</a></li>
        <% end %>
        <li class="text-light">&nbsp;&nbsp;Notes</li>
        <li><a href="/treatments">View All</a></li>
        <% if policy(:treatment).new? %>
          <li><a href="/treatments/new">Make Notes</a></li>
        <% end %>
      </ul>
    </li>
    <li class="patient-side-menu">
      <a href="#submenu3" data-toggle="collapse"><i class="fas fa-wheelchair fa-2x custom_width_1_3em"></i><label class='lbl-nav col-sm-auto'>
        Patient </label></a>
      <ul id="submenu3" class="list-unstyled collapse">
        <li><%= link_to('View All', patients_path) %></li>
        <% if current_staff.medical_staff_admin? %>
          <li><%= link_to('Register Patient', new_patient_path) %></li>
        <% end %>
      </ul>
    </li>
    <li class="ward-side-menu">
      <a href="#submenu4" data-toggle="collapse"><i class="fas fa-bed fa-2x custom_width_1_3em"></i><label class='lbl-nav col-sm-auto'>
        Ward </label></a>
      <ul id="submenu4" class="list-unstyled collapse">
        <li><%= link_to('View All', wards_path) %></li>
        <% if current_staff.medical_staff_admin? %>
          <li><%= link_to('Register Ward', new_ward_path) %></li>
        <% end %>
      </ul>
    </li>
    <li class="report-side-menu">
      <a href="#submenu5" data-toggle="collapse"><i class="fas fa-file-alt fa-2x custom_width_1_3em"></i><label class='lbl-nav col-sm-auto'>
        Report </label></a>
      <ul id="submenu5" class="list-unstyled collapse">
        <li><%= link_to('Ward List', reports_ward_list_path) %></li>
        <li><%= link_to('Medications List', reports_medications_list_path) %></li>
        <li><%= link_to('Discharge List', reports_discharge_list_path) %></li>
        <li><%= link_to('Patient Card', reports_patient_card_path) %></li>
      </ul>
    </li>
    <% if current_staff.medical_staff_admin? %>
      <li class="h-admin-side-menu">
        <a href="#submenu6" data-toggle="collapse"><i class="fas fa-hospital fa-2x custom_width_1_3em"></i><label class='lbl-nav col-sm-auto'>
          Hospital Admin </label></a>
        <ul id="submenu6" class="list-unstyled collapse">
          <li><a href="/invoices">Invoice</a></li>
          <li><a href="/teams">Teams</a></li>
          <li><a href="/staffs">Staff</a></li>
          <li><a href="/job_titles">Job Titles</a></li>
          <li><a href="/specialities">Specialities</a></li>
          <li><a href="/drugs">Drugs</a></li>
        </ul>
      </li>
    <% end %>

  </ul>
  <% if staff_signed_in? %>
    <ul class="list-unstyled float-end" style="  margin-bottom: 0px;  ">
      <li class="nav-item dropright">
        <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">
          <i class="fas fa-sign-out-alt fa-2x custom_width_1_3em"></i>
        </a>
        <div class="dropdown-menu col p-3" aria-haspopup="true" aria-expanded="false">
          <label class='font-weight-bold'> Logout now?</label>
          <div class="row">
            <div class="col-6">
              <%= link_to('Yes', destroy_staff_session_path, method: :delete, class: 'btn btn-secondary btn-sm', role: 'button') %>
            </div>
            <div class="col-6">
              <%= link_to('No', '#', class: 'btn btn-primary  btn-sm', role: 'button') %>
            </div>
          </div>
        </div>
      </li>
    </ul>
  <% end %>
  <ul class="list-unstyled float-end" style="  margin-bottom: 0px;  ">
    <li class="nav-item dropright">
      <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">
        <i class="fas fa-user-circle fa-2x custom_width_1_3em"></i>
        <label class='lbl-nav col-sm-auto'>
          <% if staff_signed_in? %>
            <%= person_full_name_helper(current_staff) %>
          <% else %>
            <%#	 In case someone got past other layouts %>
            <%= link_to('Sign in', new_staff_session_path) %>
          <% end %>
        </label>
        <% if staff_signed_in? %>
          <label class='lbl-nav col-sm-auto'><%= current_staff.role_name %></label>
        <% end %>
      </a>
      <% if staff_signed_in? %>
        <div class="dropdown-menu col-4  p-3" aria-haspopup="true" aria-expanded="false">
          <div class="row">
            <div class="col-6">
              <label class='text-light'>
                <%= link_to('Profile', staff_path(current_staff), class: 'btn btn-primary  btn-sm text-light', role: 'button') %>
              </label>
            </div>
          </div>
        </div>
      <% end %>
    </li>
  </ul>
</div>

app/views/shared/_top_nav.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark py-3 flex-column flex-md-row bd-navbar">
  <div class="navbar-collapse collapse">
    <div class="navigationButtons">
      <%= yield(:navigationButtons) if content_for?(:navigationButtons) %>
      &nbsp;
    </div>
    <ul class="navbar-nav ml-md-auto mr-3">
      <%= form_with(url: search_search_path, local: true, method: :get, html: { class: 'form-inline' }) do |search_form| %>
        <span class=""></span>
        <%= search_form.text_field(:q, class: 'form-control mr-2 search-input', type: 'text', style: 'width: 20em;',
                                   placeholder: "\u{2315}" + ' Search patient or ward name...', autocomplete: 'off', id: 'global_search_input') %>

      <% end %>
    </ul>
  </div>
</nav>